# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/paulchan/Desktop/projects/Amtal0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/paulchan/Desktop/projects/Amtal0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulchan/Desktop/projects/Amtal0/CMakeFiles /Users/paulchan/Desktop/projects/Amtal0//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulchan/Desktop/projects/Amtal0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Amtal

# Build rule for target.
Amtal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Amtal
.PHONY : Amtal

# fast build rule for target.
Amtal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/build
.PHONY : Amtal/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

src/cpp/core/FeedHandler.o: src/cpp/core/FeedHandler.cpp.o
.PHONY : src/cpp/core/FeedHandler.o

# target to build an object file
src/cpp/core/FeedHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/FeedHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/FeedHandler.cpp.o
.PHONY : src/cpp/core/FeedHandler.cpp.o

src/cpp/core/FeedHandler.i: src/cpp/core/FeedHandler.cpp.i
.PHONY : src/cpp/core/FeedHandler.i

# target to preprocess a source file
src/cpp/core/FeedHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/FeedHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/FeedHandler.cpp.i
.PHONY : src/cpp/core/FeedHandler.cpp.i

src/cpp/core/FeedHandler.s: src/cpp/core/FeedHandler.cpp.s
.PHONY : src/cpp/core/FeedHandler.s

# target to generate assembly for a file
src/cpp/core/FeedHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/FeedHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/FeedHandler.cpp.s
.PHONY : src/cpp/core/FeedHandler.cpp.s

src/cpp/core/ObjectPool.o: src/cpp/core/ObjectPool.cpp.o
.PHONY : src/cpp/core/ObjectPool.o

# target to build an object file
src/cpp/core/ObjectPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/ObjectPool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/ObjectPool.cpp.o
.PHONY : src/cpp/core/ObjectPool.cpp.o

src/cpp/core/ObjectPool.i: src/cpp/core/ObjectPool.cpp.i
.PHONY : src/cpp/core/ObjectPool.i

# target to preprocess a source file
src/cpp/core/ObjectPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/ObjectPool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/ObjectPool.cpp.i
.PHONY : src/cpp/core/ObjectPool.cpp.i

src/cpp/core/ObjectPool.s: src/cpp/core/ObjectPool.cpp.s
.PHONY : src/cpp/core/ObjectPool.s

# target to generate assembly for a file
src/cpp/core/ObjectPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/ObjectPool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/ObjectPool.cpp.s
.PHONY : src/cpp/core/ObjectPool.cpp.s

src/cpp/core/Order.o: src/cpp/core/Order.cpp.o
.PHONY : src/cpp/core/Order.o

# target to build an object file
src/cpp/core/Order.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Order.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Order.cpp.o
.PHONY : src/cpp/core/Order.cpp.o

src/cpp/core/Order.i: src/cpp/core/Order.cpp.i
.PHONY : src/cpp/core/Order.i

# target to preprocess a source file
src/cpp/core/Order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Order.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Order.cpp.i
.PHONY : src/cpp/core/Order.cpp.i

src/cpp/core/Order.s: src/cpp/core/Order.cpp.s
.PHONY : src/cpp/core/Order.s

# target to generate assembly for a file
src/cpp/core/Order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Order.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Order.cpp.s
.PHONY : src/cpp/core/Order.cpp.s

src/cpp/core/OrderBook.o: src/cpp/core/OrderBook.cpp.o
.PHONY : src/cpp/core/OrderBook.o

# target to build an object file
src/cpp/core/OrderBook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/OrderBook.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/OrderBook.cpp.o
.PHONY : src/cpp/core/OrderBook.cpp.o

src/cpp/core/OrderBook.i: src/cpp/core/OrderBook.cpp.i
.PHONY : src/cpp/core/OrderBook.i

# target to preprocess a source file
src/cpp/core/OrderBook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/OrderBook.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/OrderBook.cpp.i
.PHONY : src/cpp/core/OrderBook.cpp.i

src/cpp/core/OrderBook.s: src/cpp/core/OrderBook.cpp.s
.PHONY : src/cpp/core/OrderBook.s

# target to generate assembly for a file
src/cpp/core/OrderBook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/OrderBook.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/OrderBook.cpp.s
.PHONY : src/cpp/core/OrderBook.cpp.s

src/cpp/core/Utils.o: src/cpp/core/Utils.cpp.o
.PHONY : src/cpp/core/Utils.o

# target to build an object file
src/cpp/core/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Utils.cpp.o
.PHONY : src/cpp/core/Utils.cpp.o

src/cpp/core/Utils.i: src/cpp/core/Utils.cpp.i
.PHONY : src/cpp/core/Utils.i

# target to preprocess a source file
src/cpp/core/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Utils.cpp.i
.PHONY : src/cpp/core/Utils.cpp.i

src/cpp/core/Utils.s: src/cpp/core/Utils.cpp.s
.PHONY : src/cpp/core/Utils.s

# target to generate assembly for a file
src/cpp/core/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/core/Utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/core/Utils.cpp.s
.PHONY : src/cpp/core/Utils.cpp.s

src/cpp/data_feeds/MarketDataHandler.o: src/cpp/data_feeds/MarketDataHandler.cpp.o
.PHONY : src/cpp/data_feeds/MarketDataHandler.o

# target to build an object file
src/cpp/data_feeds/MarketDataHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/data_feeds/MarketDataHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/data_feeds/MarketDataHandler.cpp.o
.PHONY : src/cpp/data_feeds/MarketDataHandler.cpp.o

src/cpp/data_feeds/MarketDataHandler.i: src/cpp/data_feeds/MarketDataHandler.cpp.i
.PHONY : src/cpp/data_feeds/MarketDataHandler.i

# target to preprocess a source file
src/cpp/data_feeds/MarketDataHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/data_feeds/MarketDataHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/data_feeds/MarketDataHandler.cpp.i
.PHONY : src/cpp/data_feeds/MarketDataHandler.cpp.i

src/cpp/data_feeds/MarketDataHandler.s: src/cpp/data_feeds/MarketDataHandler.cpp.s
.PHONY : src/cpp/data_feeds/MarketDataHandler.s

# target to generate assembly for a file
src/cpp/data_feeds/MarketDataHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/data_feeds/MarketDataHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/data_feeds/MarketDataHandler.cpp.s
.PHONY : src/cpp/data_feeds/MarketDataHandler.cpp.s

src/cpp/main.o: src/cpp/main.cpp.o
.PHONY : src/cpp/main.o

# target to build an object file
src/cpp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/main.cpp.o
.PHONY : src/cpp/main.cpp.o

src/cpp/main.i: src/cpp/main.cpp.i
.PHONY : src/cpp/main.i

# target to preprocess a source file
src/cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/main.cpp.i
.PHONY : src/cpp/main.cpp.i

src/cpp/main.s: src/cpp/main.cpp.s
.PHONY : src/cpp/main.s

# target to generate assembly for a file
src/cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/main.cpp.s
.PHONY : src/cpp/main.cpp.s

src/cpp/server/APIServer.o: src/cpp/server/APIServer.cpp.o
.PHONY : src/cpp/server/APIServer.o

# target to build an object file
src/cpp/server/APIServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/APIServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/APIServer.cpp.o
.PHONY : src/cpp/server/APIServer.cpp.o

src/cpp/server/APIServer.i: src/cpp/server/APIServer.cpp.i
.PHONY : src/cpp/server/APIServer.i

# target to preprocess a source file
src/cpp/server/APIServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/APIServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/APIServer.cpp.i
.PHONY : src/cpp/server/APIServer.cpp.i

src/cpp/server/APIServer.s: src/cpp/server/APIServer.cpp.s
.PHONY : src/cpp/server/APIServer.s

# target to generate assembly for a file
src/cpp/server/APIServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/APIServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/APIServer.cpp.s
.PHONY : src/cpp/server/APIServer.cpp.s

src/cpp/server/Server.o: src/cpp/server/Server.cpp.o
.PHONY : src/cpp/server/Server.o

# target to build an object file
src/cpp/server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Server.cpp.o
.PHONY : src/cpp/server/Server.cpp.o

src/cpp/server/Server.i: src/cpp/server/Server.cpp.i
.PHONY : src/cpp/server/Server.i

# target to preprocess a source file
src/cpp/server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Server.cpp.i
.PHONY : src/cpp/server/Server.cpp.i

src/cpp/server/Server.s: src/cpp/server/Server.cpp.s
.PHONY : src/cpp/server/Server.s

# target to generate assembly for a file
src/cpp/server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Server.cpp.s
.PHONY : src/cpp/server/Server.cpp.s

src/cpp/server/Session.o: src/cpp/server/Session.cpp.o
.PHONY : src/cpp/server/Session.o

# target to build an object file
src/cpp/server/Session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Session.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Session.cpp.o
.PHONY : src/cpp/server/Session.cpp.o

src/cpp/server/Session.i: src/cpp/server/Session.cpp.i
.PHONY : src/cpp/server/Session.i

# target to preprocess a source file
src/cpp/server/Session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Session.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Session.cpp.i
.PHONY : src/cpp/server/Session.cpp.i

src/cpp/server/Session.s: src/cpp/server/Session.cpp.s
.PHONY : src/cpp/server/Session.s

# target to generate assembly for a file
src/cpp/server/Session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Amtal.dir/build.make CMakeFiles/Amtal.dir/src/cpp/server/Session.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/cpp/server/Session.cpp.s
.PHONY : src/cpp/server/Session.cpp.s

tests/cpp/OrderBookTest.o: tests/cpp/OrderBookTest.cpp.o
.PHONY : tests/cpp/OrderBookTest.o

# target to build an object file
tests/cpp/OrderBookTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderBookTest.cpp.o
.PHONY : tests/cpp/OrderBookTest.cpp.o

tests/cpp/OrderBookTest.i: tests/cpp/OrderBookTest.cpp.i
.PHONY : tests/cpp/OrderBookTest.i

# target to preprocess a source file
tests/cpp/OrderBookTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderBookTest.cpp.i
.PHONY : tests/cpp/OrderBookTest.cpp.i

tests/cpp/OrderBookTest.s: tests/cpp/OrderBookTest.cpp.s
.PHONY : tests/cpp/OrderBookTest.s

# target to generate assembly for a file
tests/cpp/OrderBookTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderBookTest.cpp.s
.PHONY : tests/cpp/OrderBookTest.cpp.s

tests/cpp/OrderTest.o: tests/cpp/OrderTest.cpp.o
.PHONY : tests/cpp/OrderTest.o

# target to build an object file
tests/cpp/OrderTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderTest.cpp.o
.PHONY : tests/cpp/OrderTest.cpp.o

tests/cpp/OrderTest.i: tests/cpp/OrderTest.cpp.i
.PHONY : tests/cpp/OrderTest.i

# target to preprocess a source file
tests/cpp/OrderTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderTest.cpp.i
.PHONY : tests/cpp/OrderTest.cpp.i

tests/cpp/OrderTest.s: tests/cpp/OrderTest.cpp.s
.PHONY : tests/cpp/OrderTest.s

# target to generate assembly for a file
tests/cpp/OrderTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/OrderTest.cpp.s
.PHONY : tests/cpp/OrderTest.cpp.s

tests/cpp/UtilsTest.o: tests/cpp/UtilsTest.cpp.o
.PHONY : tests/cpp/UtilsTest.o

# target to build an object file
tests/cpp/UtilsTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/UtilsTest.cpp.o
.PHONY : tests/cpp/UtilsTest.cpp.o

tests/cpp/UtilsTest.i: tests/cpp/UtilsTest.cpp.i
.PHONY : tests/cpp/UtilsTest.i

# target to preprocess a source file
tests/cpp/UtilsTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/UtilsTest.cpp.i
.PHONY : tests/cpp/UtilsTest.cpp.i

tests/cpp/UtilsTest.s: tests/cpp/UtilsTest.cpp.s
.PHONY : tests/cpp/UtilsTest.s

# target to generate assembly for a file
tests/cpp/UtilsTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/tests/cpp/UtilsTest.cpp.s
.PHONY : tests/cpp/UtilsTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Amtal"
	@echo "... Tests"
	@echo "... src/cpp/core/FeedHandler.o"
	@echo "... src/cpp/core/FeedHandler.i"
	@echo "... src/cpp/core/FeedHandler.s"
	@echo "... src/cpp/core/ObjectPool.o"
	@echo "... src/cpp/core/ObjectPool.i"
	@echo "... src/cpp/core/ObjectPool.s"
	@echo "... src/cpp/core/Order.o"
	@echo "... src/cpp/core/Order.i"
	@echo "... src/cpp/core/Order.s"
	@echo "... src/cpp/core/OrderBook.o"
	@echo "... src/cpp/core/OrderBook.i"
	@echo "... src/cpp/core/OrderBook.s"
	@echo "... src/cpp/core/Utils.o"
	@echo "... src/cpp/core/Utils.i"
	@echo "... src/cpp/core/Utils.s"
	@echo "... src/cpp/data_feeds/MarketDataHandler.o"
	@echo "... src/cpp/data_feeds/MarketDataHandler.i"
	@echo "... src/cpp/data_feeds/MarketDataHandler.s"
	@echo "... src/cpp/main.o"
	@echo "... src/cpp/main.i"
	@echo "... src/cpp/main.s"
	@echo "... src/cpp/server/APIServer.o"
	@echo "... src/cpp/server/APIServer.i"
	@echo "... src/cpp/server/APIServer.s"
	@echo "... src/cpp/server/Server.o"
	@echo "... src/cpp/server/Server.i"
	@echo "... src/cpp/server/Server.s"
	@echo "... src/cpp/server/Session.o"
	@echo "... src/cpp/server/Session.i"
	@echo "... src/cpp/server/Session.s"
	@echo "... tests/cpp/OrderBookTest.o"
	@echo "... tests/cpp/OrderBookTest.i"
	@echo "... tests/cpp/OrderBookTest.s"
	@echo "... tests/cpp/OrderTest.o"
	@echo "... tests/cpp/OrderTest.i"
	@echo "... tests/cpp/OrderTest.s"
	@echo "... tests/cpp/UtilsTest.o"
	@echo "... tests/cpp/UtilsTest.i"
	@echo "... tests/cpp/UtilsTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

